### ISSUE TITLE
Hekate : only 1 entry now ?

### ISSUE THREAD

**Issue by Draky50110** [THZoria/AtmoPack-Vanilla#3]
Hello.

Using your pack with hekate.ini, it has now only one entry to boot Atmo, you removed the 2 others ?

Why ?

Possible to have them back ? Like booting sysMMC.

Booting emuMMC on Atmo has different options now, more than before, is it normal ?

Thanks.

**Comment by THZoria** [comment]
Hello

I use only one entry because the fss0 startup is a bit barbaric and prevents the use of tinfoil.
The current configuration starts "fusee primary" which starts the sysNAND if you don't have an emuNAND, and if you have an emuNAND it will start automatically.This is more to avoid users getting lost with different configurations and to allow tinfoil to work (that's why there is no sigpatch for Hekate and only for fusee)

**Comment by Draky50110** [comment]
Thanks for explanation :)

So could it be possible to add ony one more entry : "boot sysMMC without Atmo" ?

**Comment by THZoria** [comment]
You can integrate it if you want in the hekate_ipl but I won't add it in my pack because I don't want to mix the fss0 and fusee startup
